id: xss-reflect-fuzzer

info:
  name: html-reflect-fuzzer
  author: erickfernandox
  severity: medium
  description: |
    Verifica parametros ocultos que refletem dentro do HTML da pagina
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.1
    cwe-id: CWE-601
  metadata:
    max-request: 2
  tags: fuzzer, generic

http:
  - method: GET
    path:
      - "{OutputGoesHere}"
      - "{{BaseURL}}%27%22%20test=fx-URI"     
      - "{{BaseURL}}//%27%22%20test=fx-URI"                      
      - "{{BaseURL}}//%27%22%20test=fx-URI/%2f.."             
      - "{{BaseURL}}////%27%22%20test=fx-URI"                  
      - "{{BaseURL}}/%0A/%27%22%20test=fx-URI"                  
      - "{{BaseURL}}/%0A%5c%27%22%20test=fx-URI"                        
      - "{{BaseURL}}/%0D/%27%22%20test=fx-URI"                   
      - "{{BaseURL}}/%0D%5c%27%22%20test=fx-URI"               
      - "{{BaseURL}}/<>/%27%22%20test=fx-URI"                        
      - "{{BaseURL}}/%5c%27%22%20test=fx-URI"                  
      - "{{BaseURL}}/%27%22>%27%22%20test=fx-URI"
      - "{{BaseURL}}/JyIgb25tb3VzZW92ZXI9ZWZ4LWI2NAo="
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:                    
          - "'\" test=fx-"

          
        condition: and

      - type: word
        words:
          - "text/html"
        part: header

        condition: and

      - type: status
        status:
          - 200
          - 404